"""Pure SVG architecture renderer for GEO analysis reports."""

from __future__ import annotations

from html import escape
from typing import Dict, List

WIDTH = 1200
HEIGHT = 940

LAYER_DEFINITIONS = [
    {"label": "Input", "y": 88, "color": "#1f5eff"},
    {"label": "Analysis", "y": 200, "color": "#13c2c2"},
    {"label": "Entity Graph", "y": 312, "color": "#7c4dff"},
    {"label": "Keyword Clusters", "y": 424, "color": "#f59e0b"},
    {"label": "Search Intent", "y": 536, "color": "#eb2f96"},
    {"label": "Content Framework", "y": 648, "color": "#2f9e44"},
    {"label": "Export", "y": 760, "color": "#1f5eff"},
]


def _escape(value) -> str:
    return escape(str(value or ""), quote=True)


def _truncate(value: str, limit: int = 26) -> str:
    value = str(value or "").strip()
    if len(value) <= limit:
        return value
    return f"{value[: limit - 1]}..."


def _wrap(value: str, limit: int = 16) -> list:
    words = str(value or "").split()
    lines = []
    current = ""
    for word in words:
        if not current:
            current = word
        elif len(current) + len(word) + 1 <= limit:
            current += " " + word
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines[:3] or [""]


def render_architecture_svg(
    title: str,
    framework: Dict,
    keyword_clusters: List[Dict],
    intents: List[Dict],
) -> str:
    """Return a standalone SVG with groups title, layers, nodes, edges and labels."""
    nodes, edges, labels = _build_diagram(framework, keyword_clusters, intents)
    style = """
    .geo-title { font: 700 34px -apple-system, "Segoe UI", sans-serif; fill: #17233d; }
    .geo-subtitle { font: 400 15px -apple-system, sans-serif; fill: #697b8c; }
    .geo-layer-label { font: 700 14px -apple-system, sans-serif; fill: #17233d; }
    .geo-node { fill: #ffffff; stroke-width: 2; }
    .geo-node-label { font: 600 13px -apple-system, sans-serif; fill: #17233d; }
    .geo-edge { stroke: #a0adbf; stroke-width: 2; fill: none; }
    .geo-edge-arrow { fill: #a0adbf; }
    .geo-footer { font: 400 12px -apple-system, sans-serif; fill: #8c9aab; }
    """
    node_elements = []
    for node in nodes:
        node_elements.append(
            f'<g id="node-{node["id"]}">'
            f'<rect class="geo-node" x="{node["x"]}" y="{node["y"]}" width="{node["w"]}" '
            f'height="{node["h"]}" rx="12" fill="{node.get("fill", "#ffffff")}" '
            f'stroke="{node.get("color", "#1f5eff")}"/>'
            f'<text class="geo-node-label" x="{node["x"] + 14}" y="{node["y"] + 22}">'
            f'{_escape(_truncate(node["label"], 24))}</text>'
            f'</g>'
        )
    edge_elements = []
    for edge in edges:
        edge_elements.append(
            f'<g id="edge-{edge["id"]}">'
            f'<line class="geo-edge" x1="{edge["x1"]}" y1="{edge["y1"]}" x2="{edge["x2"]}" y2="{edge["y2"]}"/>'
            f'<path class="geo-edge-arrow" d="M {edge["x2"]} {edge["y2"]} l -8 -4 v 8 z"/>'
            f'</g>'
        )
    layer_elements = []
    label_elements = []
    for layer in LAYER_DEFINITIONS:
        layer_elements.append(
            f'<g id="layer-{_escape(layer["label"]).lower().replace(" ", "-")}">'
            f'<rect x="42" y="{layer["y"] - 22}" width="1116" height="66" rx="12" '
            f'fill="{layer["color"]}" fill-opacity="0.06" stroke="{layer["color"]}" stroke-opacity="0.18"/>'
            f'</g>'
        )
        label_elements.append(
            f'<text class="geo-layer-label" x="64" y="{layer["y"] + 6}" fill="{layer["color"]}">'
            f'{_escape(layer["label"])}</text>'
        )

    content_boxes = []
    for index, item in enumerate(framework.get("structure", [])[:4]):
        heading = _escape(_truncate(item.get("heading", ""), 32))
        content_boxes.append(
            f'<text x="90" y="{826 + index * 22}" fill="#17233d" font-size="13" font-weight="600">{heading}</text>'
        )

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg id="geo-architecture" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="100%" height="auto" role="img" aria-label="{_escape(title)}">
  <style>{style}</style>
  <rect x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="20" fill="#f8fafc"/>
  <g id="title">
    <text class="geo-title" x="64" y="52">{_escape(title)}</text>
    <text class="geo-subtitle" x="66" y="76">GEO analysis architecture with entities, keywords, intents and content framework</text>
  </g>
  <g id="layers">{''.join(layer_elements)}</g>
  <g id="edges">{''.join(edge_elements)}</g>
  <g id="nodes">{''.join(node_elements)}</g>
  <g id="labels">{''.join(label_elements)}{''.join(content_boxes)}</g>
  <text class="geo-footer" x="64" y="{HEIGHT - 20}">Generated by GEO Production System | {_escape(title)}</text>
</svg>
"""


def _build_diagram(framework: Dict, keyword_clusters: List[Dict], intents: List[Dict]):
    nodes = []
    edges = []
    node_id = 0
    edge_id = 0

    def add_node(label, layer_index, position, color, fill="#ffffff"):
        nonlocal node_id
        node_id += 1
        node = {
            "id": f"n{node_id}",
            "label": label,
            "x": 120 + position * 250,
            "y": LAYER_DEFINITIONS[layer_index]["y"] - 12,
            "w": 220,
            "h": 52,
            "color": color,
            "fill": fill,
            "layer": layer_index,
        }
        nodes.append(node)
        return node

    def add_edge(source, target):
        nonlocal edge_id
        edge_id += 1
        edges.append(
            {
                "id": f"e{edge_id}",
                "x1": source["x"] + source["w"],
                "y1": source["y"] + source["h"] / 2,
                "x2": target["x"],
                "y2": target["y"] + target["h"] / 2,
            }
        )

    input_node = add_node("Article / URL / Markdown / TXT", 0, 1, "#1f5eff")
    analysis_node = add_node("Article Analysis", 1, 1, "#13c2c2")
    add_edge(input_node, analysis_node)

    entity_labels = [item.get("name", "") for item in (framework.get("entity_summary", []) or [])][:3]
    entity_labels = entity_labels or ["Brand", "Product", "Organization"]
    entity_nodes = [
        add_node(label, 2, index, "#7c4dff") for index, label in enumerate(entity_labels[:4])
    ]
    for entity_node in entity_nodes[:2]:
        add_edge(analysis_node, entity_node)

    cluster_labels = [cluster.get("cluster", "") for cluster in keyword_clusters[:4]]
    cluster_labels = cluster_labels or ["Primary", "Secondary", "Semantic", "FAQ"]
    cluster_nodes = [
        add_node(label, 3, index, "#f59e0b") for index, label in enumerate(cluster_labels[:4])
    ]
    for cluster_node in cluster_nodes[:2]:
        add_edge(entity_nodes[0], cluster_node)

    intent_labels = [item.get("label", "") for item in intents[:4]]
    intent_labels = intent_labels or ["Informational", "Commercial", "Transactional", "Navigational"]
    intent_nodes = [
        add_node(label, 4, index, "#eb2f96") for index, label in enumerate(intent_labels[:4])
    ]
    for intent_node in intent_nodes[:2]:
        add_edge(cluster_nodes[0], intent_node)

    framework_node = add_node("Framework / FAQ / Schema", 5, 1, "#2f9e44")
    add_edge(intent_nodes[0], framework_node)

    export_node = add_node("MD / HTML / PDF / SVG / PNG", 6, 1, "#1f5eff")
    add_edge(framework_node, export_node)

    return nodes, edges, []
