"""Optional PNG export for the SVG architecture diagram."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

LOGGER = logging.getLogger(__name__)

try:
    import cairosvg
except Exception:  # pragma: no cover - optional dependency requires native cairo
    cairosvg = None


def export_png(svg: str, output_path: Path) -> Optional[Path]:
    """Render architecture.svg to architecture.png when cairosvg is available."""
    if cairosvg is None:
        LOGGER.warning("cairosvg is not available; using built-in PNG fallback")
        return _export_fallback_png(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=str(output_path), output_width=1600)
    LOGGER.info("PNG architecture written: %s", output_path)
    return output_path


def _export_fallback_png(output_path: Path) -> Path:
    from PIL import Image, ImageDraw, ImageFont

    output_path.parent.mkdir(parents=True, exist_ok=True)
    width, height = 1200, 900
    image = Image.new("RGB", (width, height), "#f8fafc")
    draw = ImageDraw.Draw(image)
    try:
        font = ImageFont.load_default(size=16)
        title_font = ImageFont.load_default(size=30)
    except TypeError:  # older Pillow versions
        font = ImageFont.load_default()
        title_font = font

    draw.text((40, 30), "GEO Analysis Architecture", fill="#17233d", font=title_font)
    layers = [
        ("Input", 80),
        ("Article Analysis", 190),
        ("Entity Graph", 300),
        ("Keyword Clusters", 410),
        ("Search Intent", 520),
        ("Content Framework", 630),
        ("Export", 740),
    ]
    colors = ["#1f5eff", "#13c2c2", "#7c4dff", "#f59e0b", "#eb2f96", "#2f9e44", "#1f5eff"]
    for index, (label, y) in enumerate(layers):
        color = colors[index]
        draw.rounded_rectangle(
            (40, y - 24, 1160, y + 44),
            radius=12,
            fill=hex_to_rgb(color, 0.06),
            outline=color,
            width=2,
        )
        draw.text((55, y - 8), label, fill=color, font=font)
        box_x = 260 + (index % 2) * 280
        draw.rounded_rectangle(
            (box_x, y - 12, box_x + 220, y + 42),
            radius=10,
            fill="#ffffff",
            outline=color,
            width=2,
        )
        draw.text((box_x + 12, y + 2), label, fill="#17233d", font=font)
        if index < len(layers) - 1:
            draw.line(
                (box_x + 220, y + 15, box_x + 260, layers[index + 1][1] + 15),
                fill="#a0adbf",
                width=2,
            )

    draw.text((40, 860), "Generated by GEO Production System", fill="#8c9aab", font=font)
    image.save(output_path, format="PNG")
    LOGGER.info("Fallback PNG architecture written: %s", output_path)
    return output_path


def hex_to_rgb(value: str, alpha: float = 1.0):
    value = value.lstrip("#")
    rgb = tuple(int(value[index : index + 2], 16) for index in (0, 2, 4))
    if alpha >= 1:
        return rgb
    return tuple(int(channel * alpha + 255 * (1 - alpha)) for channel in rgb)
